// gen-theme.js — converts the design's oklch tokens to RN-friendly hex/rgba and
// writes src/theme.js. Run once: `node gen-theme.js`.
const fs = require("fs");
const path = require("path");

function oklchToRgb(L, C, H) {
  const h = (H * Math.PI) / 180;
  const a = C * Math.cos(h);
  const b = C * Math.sin(h);
  const l_ = L + 0.3963377774 * a + 0.2158037573 * b;
  const m_ = L - 0.1055613458 * a - 0.0638541728 * b;
  const s_ = L - 0.0894841775 * a - 1.291485548 * b;
  const l = l_ ** 3, m = m_ ** 3, s = s_ ** 3;
  let r = 4.0767416621 * l - 3.3077115913 * m + 0.2309699292 * s;
  let g = -1.2684380046 * l + 2.6097574011 * m - 0.3413193965 * s;
  let bl = -0.0041960863 * l - 0.7034186147 * m + 1.707614701 * s;
  const gamma = (x) => {
    x = Math.max(0, Math.min(1, x));
    return x <= 0.0031308 ? 12.92 * x : 1.055 * Math.pow(x, 1 / 2.4) - 0.055;
  };
  return [gamma(r), gamma(g), gamma(bl)].map((v) => Math.round(v * 255));
}
const hex = (L, C, H) => {
  const [r, g, b] = oklchToRgb(L, C, H);
  return "#" + [r, g, b].map((v) => v.toString(16).padStart(2, "0")).join("");
};
const rgba = (L, C, H, alpha) => {
  const [r, g, b] = oklchToRgb(L, C, H);
  return `rgba(${r}, ${g}, ${b}, ${alpha})`;
};

const light = {
  surface: hex(0.97, 0.008, 75),
  surface2: hex(0.95, 0.011, 75),
  surface3: hex(0.92, 0.013, 75),
  ink: hex(0.21, 0.012, 60),
  ink2: hex(0.42, 0.012, 60),
  ink3: hex(0.58, 0.012, 60),
  hairline: rgba(0.88, 0.012, 75, 0.8),
  hairlineStrong: hex(0.82, 0.014, 75),
  accent: hex(0.66, 0.16, 35),
  accentInk: hex(0.99, 0.008, 75),
  accentTint: hex(0.93, 0.05, 35),
  positive: hex(0.62, 0.12, 155),
  positiveTint: hex(0.92, 0.045, 155),
  warning: hex(0.7, 0.13, 75),
  warningTint: hex(0.93, 0.05, 75),
  danger: hex(0.58, 0.18, 25),
  // glass
  glassBg: rgba(1, 0, 0, 0.4),
  glassBgStrong: rgba(1, 0, 0, 0.6),
  glassTint: "light",
  glassBorder: rgba(1, 0, 0, 0.6),
  glassBorderBottom: rgba(0.2, 0.01, 60, 0.06),
  // screen background glow corners
  bgGlow1: rgba(0.86, 0.13, 35, 0.9),
  bgGlow2: rgba(0.83, 0.13, 65, 0.8),
  bgGlow3: rgba(0.84, 0.1, 250, 0.65),
  bgGlow4: rgba(0.86, 0.1, 320, 0.6),
  bgBase1: hex(0.97, 0.012, 75),
  bgBase2: hex(0.95, 0.018, 75),
  stageGlow: hex(0.93, 0.025, 35),
  stageBase: hex(0.96, 0.008, 75),
  // map
  mapBase: hex(0.93, 0.008, 75),
  mapGrid: hex(0.86, 0.012, 75),
  mapGreen: hex(0.9, 0.04, 145),
  mapGreenInk: hex(0.45, 0.04, 145),
  mapWater: hex(0.86, 0.04, 235),
  mapWaterInk: hex(0.5, 0.04, 235),
  mapRoad: "#ffffff",
  mapRoadEdge: hex(0.82, 0.012, 75),
  mapStreetInk: hex(0.45, 0.012, 75),
  youPin: hex(0.55, 0.18, 250),
  alertBlue: hex(0.55, 0.18, 250),
  // placeholder gradient pair builder uses hue at runtime
  permGlow1: hex(0.92, 0.09, 35),
  permGlow2: hex(0.94, 0.06, 250),
};

const dark = {
  surface: hex(0.18, 0.008, 60),
  surface2: hex(0.22, 0.01, 60),
  surface3: hex(0.26, 0.012, 60),
  ink: hex(0.97, 0.008, 75),
  ink2: hex(0.78, 0.008, 75),
  ink3: hex(0.6, 0.01, 75),
  hairline: rgba(0.32, 0.012, 60, 0.7),
  hairlineStrong: hex(0.4, 0.014, 60),
  accent: hex(0.74, 0.14, 35),
  accentInk: hex(0.18, 0.008, 60),
  accentTint: hex(0.32, 0.06, 35),
  positive: hex(0.72, 0.12, 155),
  positiveTint: hex(0.32, 0.06, 155),
  warning: hex(0.78, 0.13, 75),
  warningTint: hex(0.32, 0.06, 75),
  danger: hex(0.58, 0.18, 25),
  glassBg: rgba(0.28, 0.012, 60, 0.5),
  glassBgStrong: rgba(0.3, 0.012, 60, 0.72),
  glassTint: "dark",
  glassBorder: rgba(1, 0, 0, 0.14),
  glassBorderBottom: rgba(0, 0, 0, 0.25),
  bgGlow1: rgba(0.4, 0.13, 35, 0.95),
  bgGlow2: rgba(0.36, 0.12, 65, 0.85),
  bgGlow3: rgba(0.32, 0.12, 250, 0.75),
  bgGlow4: rgba(0.36, 0.1, 320, 0.65),
  bgBase1: hex(0.16, 0.012, 60),
  bgBase2: hex(0.13, 0.012, 60),
  stageGlow: hex(0.2, 0.04, 35),
  stageBase: hex(0.12, 0.008, 60),
  mapBase: hex(0.26, 0.012, 60),
  mapGrid: hex(0.32, 0.012, 60),
  mapGreen: hex(0.4, 0.05, 145),
  mapGreenInk: hex(0.8, 0.06, 145),
  mapWater: hex(0.3, 0.05, 235),
  mapWaterInk: hex(0.7, 0.05, 235),
  mapRoad: hex(0.42, 0.01, 60),
  mapRoadEdge: hex(0.5, 0.012, 60),
  mapStreetInk: hex(0.7, 0.012, 75),
  youPin: hex(0.62, 0.18, 250),
  alertBlue: hex(0.62, 0.18, 250),
  permGlow1: hex(0.34, 0.1, 35),
  permGlow2: hex(0.28, 0.08, 250),
};

const out = `// theme.js — AUTO-GENERATED by gen-theme.js from the design's oklch tokens.
// Light + dark palettes plus shared type/radius scales.

export const fonts = {
  sans: "Inter_400Regular",
  sansMed: "Inter_500Medium",
  sansSemi: "Inter_600SemiBold",
  sansBold: "Inter_700Bold",
  serif: "InstrumentSerif_400Regular",
  serifItalic: "InstrumentSerif_400Regular_Italic",
  mono: "JetBrainsMono_400Regular",
  monoMed: "JetBrainsMono_500Medium",
};

export const radius = { sm: 10, md: 16, lg: 22, xl: 28, pill: 999 };

export const palettes = {
  light: ${JSON.stringify(light, null, 2)},
  dark: ${JSON.stringify(dark, null, 2)},
};

export function getTheme(dark) {
  return dark ? palettes.dark : palettes.light;
}
`;

fs.writeFileSync(path.join(__dirname, "src", "theme.js"), out);
console.log("Wrote src/theme.js");
console.log("accent(light)=", light.accent, " accent(dark)=", dark.accent);
console.log("ink=", light.ink, " surface=", light.surface);
